const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const RELOAD_DATA = 'RELOAD_DATA';
const SAVE_INFORMATION = 'SAVE_INFORMATION';
export {
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOGIN_SUCCESS,
    RELOAD_DATA,
    SAVE_INFORMATION
}
